Feature
SimonGrchevski/ChosedName pull request #3
Opened 2021-11-26 21:22 UTC by SimonGrchevski

[Presentation](https://www.loom.com/share/a4eb0a9724ef446aba1da12f8f0401e6)

-  Add devise
-  Add a simple splash page with the links sign up and log in
-  The user must log with  full name, email, and password

- Add Home page
-  For each category, the user can see their name, icon, and the total amount of all the transactions that belong to that category.
- Add Products actions
- Add Deals actions
- Add back buttons to the pages
- Add validations

- Add model,request and integration tests

2021-11-26 23:21 UTC, rloterh requested changes
Hi Simon, 

You did great on this project, and for making the changes requested in the previous review(s)! 👏👏 
There are however a few issues that you still need to work on to go to the next project but you are almost there! 🚦  🚦  

## Good Points 👍
- Descriptive Pull Request
- App is running as intended
- Devise used for authentication
- Postgresql database used for project
- Good video presentation
- No linter errors



## Required Changes ♻️
_Kindly check the comments under the review._

<br>
Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 4 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-26 23:21 UTC, rloterh commented on README.md
> -# README
Your _ReadMe_ needs some improvements so as to make it appear more professional. Kindly note that _ReadMe_ is mostly the first place that visitors of this project's repository will go and therefore it has to be very detailed and professional. Also, it needs to be done well with respect to this project,  which will likely feature on your portfolio. Kindly ensure to improve upon these aspects of your ReadMe. 
- [x] _Project description_, _how to set up_, _run and test this project_ **should be detailed, clear, and well** organized.
- [x] The _code_ aspects in each procedure should be quoted with **backticks**.
- [x] All _typos_ **should be corrected**. You can crosscheck by installing the [Grammarly plugin](https://www.grammarly.com/)

2021-11-26 23:21 UTC, rloterh commented on README.md
> +## Authors
- [x] Kindly change the header title _Authors_ to _Author_, as this project is done solely. This will make your ReadMe appear more professional.

2021-11-26 23:21 UTC, rloterh commented on README.md
> +## Acknowledgments
- [x] It's a nice and smart thing to give appropriate credit to **[Gregoire Vella on Behance](https://www.behance.net/gregoirevella)**, the author of [the original design](https://www.behance.net/gregoirevella)), as required by the [Creative Commons License](https://creativecommons.org/licenses/). Kindly ensure to add this under the **Acknowledgements** section of your ReadMe.

2021-11-26 23:21 UTC, rloterh commented on app/views/products/index.html.erb
> +    <%= link_to 'Add new product', new_product_path, class:'btn btn-success w-100 border-white'%>
- [ ] The Add new product button is not accessible when a user first logins. It's appearing half-hidden during the first attempt to add a product, and it's the same when the height of the mobile view is increased. Kind;y ensure to improve upon this aspect.

**Your Add new product page:**
![image](https://user-images.githubusercontent.com/12745474/143660316-54f2a0a7-53b2-4061-a881-942a19e4ec1d.png)

2021-11-27 01:05 UTC, descholar-ceo approved these changes
Hi @SimonGrchevski , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-27 01:41 UTC, merged